INSERT INTO REGIONS ( NAME, REGION_INITIALS) VALUES ('Western Cape', 'ZA-WC');
INSERT INTO REGIONS ( NAME, REGION_INITIALS) VALUES ('Gauteng', 'ZA-GT');
INSERT INTO REGIONS ( NAME, REGION_INITIALS) VALUES ('KwaZulu Natal', 'ZA-NL');
INSERT INTO REGIONS ( NAME, REGION_INITIALS) VALUES ('Mpumalanga', 'ZA-MP');
INSERT INTO REGIONS ( NAME, REGION_INITIALS) VALUES ('Free State', 'ZA-FS');
INSERT INTO REGIONS ( NAME, REGION_INITIALS) VALUES ('Eastern Cape', 'ZA-EC');
INSERT INTO REGIONS ( NAME, REGION_INITIALS) VALUES ('Limpopo', 'ZA-LP');
INSERT INTO REGIONS ( NAME, REGION_INITIALS) VALUES ('Northern Cape', 'ZA-NC');
INSERT INTO REGIONS ( NAME, REGION_INITIALS) VALUES ('North West', 'ZA-NW');
