INSERT INTO SUBJECTS (SUBJECT_NAME, REGIONS_ID) VALUES ('Mathematics', 1);
INSERT INTO SUBJECTS (SUBJECT_NAME, REGIONS_ID) VALUES ('Geography', 2);
INSERT INTO SUBJECTS (SUBJECT_NAME, REGIONS_ID) VALUES ('Life Sciences', 3);
INSERT INTO SUBJECTS (SUBJECT_NAME, REGIONS_ID) VALUES ('History', 4);
INSERT INTO SUBJECTS (SUBJECT_NAME, REGIONS_ID) VALUES ('Consumer Studies', 5);
INSERT INTO SUBJECTS (SUBJECT_NAME, REGIONS_ID) VALUES ('Accounting', 6);
INSERT INTO SUBJECTS (SUBJECT_NAME, REGIONS_ID) VALUES ('Computer Science', 7);
INSERT INTO SUBJECTS (SUBJECT_NAME, REGIONS_ID) VALUES ('Mathematical Literacy', 8);
INSERT INTO SUBJECTS (SUBJECT_NAME, REGIONS_ID) VALUES ('History', 9);