INSERT INTO SCHOOLS (SCHOOL_NAME, SCHOOL_REG_STATUS, SUBJECT_ID, REGIONS_ID) VALUES ('Osizweni High', 'Registered', 3, 3);
INSERT INTO SCHOOLS (SCHOOL_NAME, SCHOOL_REG_STATUS, SUBJECT_ID, REGIONS_ID) VALUES ('Khayelitsha High', 'Registered', 1, 1);
INSERT INTO SCHOOLS (SCHOOL_NAME, SCHOOL_REG_STATUS, SUBJECT_ID, REGIONS_ID) VALUES ('Bopasenatla Secondary School', 'Registered', 2, 2);
INSERT INTO SCHOOLS (SCHOOL_NAME, SCHOOL_REG_STATUS, SUBJECT_ID, REGIONS_ID) VALUES ('Curro Nelspruit', 'Registered', 4, 4);
INSERT INTO SCHOOLS (SCHOOL_NAME, SCHOOL_REG_STATUS, SUBJECT_ID, REGIONS_ID) VALUES ('Sivuyiseni Public Primary School', 'Registered', 5, 5);
INSERT INTO SCHOOLS (SCHOOL_NAME, SCHOOL_REG_STATUS, SUBJECT_ID, REGIONS_ID) VALUES ('Alphedale High School', 'Registered', 6, 6);
INSERT INTO SCHOOLS (SCHOOL_NAME, SCHOOL_REG_STATUS, SUBJECT_ID, REGIONS_ID) VALUES ('Eagles Nest Christian School', 'Registered', 7, 7);
INSERT INTO SCHOOLS (SCHOOL_NAME, SCHOOL_REG_STATUS, SUBJECT_ID, REGIONS_ID) VALUES ('Kimberley Girls High School', 'Registered', 8, 8);
INSERT INTO SCHOOLS (SCHOOL_NAME, SCHOOL_REG_STATUS, SUBJECT_ID, REGIONS_ID) VALUES ('The Settlers High School', 'Registered', 9, 9);